apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: login-service
spec:
  host: login-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: v1
      labels:
        version: v1